### 1-3-1. 넘파이(Numpy) 라이브러리 

In [ ]:
import numpy as np

# 1. 배열(array) 생성
array = np.array([1, 2, 3, 4, 5])
print(array)
# [1 2 3 4 5]

# 2. 자주 사용되는 함수
a = np.arange(4).reshape((2,2))
print(a)
'''
[[0 1]
 [2 3]]
'''
print(np.max(a))  # 3
print(np.max(a, axis=0))  # [2 3]
print(np.max(a, axis=1))  # [1 3]

# 3. np.argsort()
# 올림차순 정렬
arr = np.array([50, 20, 40, 10])
idx = np.argsort(arr)
print(idx)  # [3 2 1 0]
print(arr[idx])  # array([10, 20, 40, 50])

# 내림차순 정렬
arr = np.array([50, 20, 40, 10])
idx = np.argsort(arr)[::-1]  # 슬라이싱 문법 [start:stop:step]
print(idx)  # [0 2 1 3]
print(arr[idx])  # array([50, 40, 20, 10])

[1 2 3 4 5]
[[0 1]
 [2 3]]
3
[2 3]
[1 3]
[3 1 2 0]
[10 20 40 50]
[0 2 1 3]
[50 40 20 10]
